version: '3'

services:
  spoopy-api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/app
    ports:
      - 8282:8000

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres:
