version: '3'

services:
  spoopy-api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/app
    ports:
      - 8282:8000

  postgres:
    image: postgres:10-alpine
#    ports:
#      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  postgres:
